name: run-benchmark

on: ["workflow_dispatch", "workflow_call"]

permissions:
  contents: write

jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: setup project
        uses: ./.github/actions/setup

      - name: build-benchmark and run-benchmark
        uses: ./.github/actions/run-benchmark
